name: Bank
on: [push]
jobs:
  BuildTest:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: prepare
        run: |
          sudo apt-get install lcov

      - name: building
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTS=ON -DCOVERALLS=ON ..
          make

      - name: test
        run: |
          ctest

      - name: coverage
        run: |
          cd ..
          lcov --capture --directory . --output-file lcov.info --test-name bank_test --no-external

      #- name: Coveralls
      #  run: coveralls -t ${{ secrets.coveralls_token }} --root . -E ".*external.*" -E ".*tests.*"

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./build/lcov.info
          github-token: ${{ github.token }}