name: Bank
on: [push]
jobs:
  BankBuildTest:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: building
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTS=ON -DCOVERALLS=OFF ..
          make 
          ctest

      #- name: test
      #  run: |
      #    cd build
      #    ctest

  Coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: building
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTS=OFF -DCOVERALLS=ON ..
          make --coverage

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}






          
