name: Coverage
on: [push]
jobs:
  Coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: building
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTS=OFF -DCOVERALLS=ON ..
          make 

      - name: Coveralls
        run: coveralls -t ${{ secrets.coveralls_token }}

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}


